import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from 'next/font/google';

const outfit = Outfit({
  subsets: ['latin'], // Dukungan subset karakter
  variable: '--font-outfit', // Custom CSS variable
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Semua bobot
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
